name: Build and Deploy

on:
  push:
    branches: [ "master" ]

env:
  NETCORE_VERSION: "8.0.x"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  SRC: "/home/runner/work/QuickForm/QuickForm/src"
  PROJECT_NAME: "QuickForm"

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Change base href in host file to match gh repo name 🏷️
        run: |
          cd ${{ env.SRC }}/${{ env.PROJECT_NAME }}
          REPO_NAME=$(echo "${{ github.repository }}" | awk -F '/' '{print $NF}')
          sed -i 's/<base href="\/"[[:blank:]]*\/>/<base href="\/'$REPO_NAME'\/" \/>/g' ./wwwroot/index.html

      - name: Publish 📦
        run: dotnet publish ${{ env.SRC }}/${{ env.PROJECT_NAME }} --configuration Release --output dist

      - name: Create .nojekyll file 📁
        run: touch dist/wwwroot/.nojekyll

      - name: Copy index.html to 404.html 📄
        run: |
          cp dist/wwwroot/index.html dist/wwwroot/404.html  

      - name: Deploy to gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/wwwroot